### ISSUE TITLE
Intermittent boot and screen flicker.

### ISSUE THREAD

**Issue by kog001** [bobricius/Armachat-circuitpython#10]
I am building 5 pieces of the Compact version. The pcb's came from pcb way, the bss123 mosfets came from here https://www.tme.eu/ro/details/bss123ixtsa1/tranzistori-canal-n-smd/infineon-technologies/. the pi picos are original raspberrys. The screens have been ordered from ali and all 5 behave the same - https://www.aliexpress.com/item/4001220638683.html?spm=a2g0o.order_list.order_list_main.4.4cd21802nwPZro

As the title describes, when I connect the stripped board with just the display and the rpi board, if I get lucky enough for the thing to boot, the screen flickers and the rpi freezes and disconnects. I do not know what to try anymore. At first I thought it was the chinese LORA module, but on the second armachat pcb I did not even solder it. The behavior is the same if I power it through an external battery.

Do you have any suggestions?

Thank you.

**Comment by bobricius** [comment]
upload latest circuitpython, 8 .... then try copy all from
https://github.com/bobricius/Armachat-circuitpython/tree/main/New%20software
in config
https://github.com/bobricius/Armachat-circuitpython/blob/main/New%20software/lib/config.py
enable
keyboard_model="keys30"
display_model= "display320x240"
model_lora = "compact"

or try this gaming firmware https://github.com/fruit-bat/pico-zxspectrum/blob/main/uf2/ZxSpectrumPicomputerMax.uf2
maybe display show something
check display connection

**Comment by kog001** [comment]
Unfortunately I can not reliably connect to the pi. I loaded the program before soldering it on the board and then I soldered it on the board. It sometimes boots, and the screen works as it should, running the pi diagnosis and start-up. As it loads up to "press numbers 0-9" it either shuts down, flickers or freezes. 

Update: While I was writing this, I thought of de soldering the display again. Result: the pi connects to the pc again. I soldered another new display and the issue came back. I tried three displays and got the same issue. They can't be all bad, can they? is it a power related issue? Do the screens draw that much?

**Comment by bobricius** [comment]
I not found any problem with displays, check if display bottom metal part not shorting something on board ...

**Comment by kog001** [comment]
I had insulated the back of the display with tape. Even with the display hanging by the connection, the problem persists. The only thing left to check/redo is the soldered connection to the board. 

Thank you very much for the help!

**Comment by kog001** [comment]
No luck. I have a stripped pcb with only the buttons, smd's and the PI installed. It still connects intermittently to the pc. Next step is to build another device and send it to a pro, maybe he can find the fault.

**Comment by kog001** [comment]
I finally found the issue. The soldering pads are very close together and it is very easy to short them. The connections might look good but behind the foil they may be arching.
