### ISSUE TITLE
boot_out error

### ISSUE THREAD

**Issue by kog001** [bobricius/Armachat-circuitpython#11]
One issue solved, a new one appeared.

I installed the new software and configured the config.py as indicated.
The display shows only the snake in the corner.

The boot_out file gives the following error:
boot.py output:
Traceback (most recent call last):
  File "boot.py", line 11, in < module>
  File "/lib/picomputer.py", line 2, in < module>
  File "/lib/config.py", line 229, in < module>
IndexError: Group index out of range

Any ideas?

Thanks.

**Comment by bobricius** [comment]
Cpython8font8x16regular.uf2 is uploaded?
check display configuration

**Comment by kog001** [comment]
You were right,

I was loading the wrong Cpython version.

Thank you!
