### ISSUE TITLE
Firmware for raspberry pi pico for armachat and picomputer

### ISSUE THREAD

**Issue by APToni** [bobricius/Armachat-circuitpython#9]
Good afternoon, do you have instructions for beginners to install software for armachat and picocomputer? based on pi pico.

**Comment by bobricius** [comment]
[From doc](https://github.com/Kayto/Armachat-Compact-Documentation)

**Software Installation**
Once assembly is complete you are ready to install the Armachat software to the board. There are two main steps.
1. Upload of the CircuitPython binary to the Raspberry Pi Pico board.
2. Upload of Armachat COMPACT code to the flash memory.
The CircuitPython binary is available from
https://circuitpython.org/board/raspberry_pi_pico/
The Armachat COMPACT code is available from
https://github.com/bobricius/Armachat-circuitpython
**Step 1** - Uploading CircuitPython binary to the Raspberry Pi Pico
a) Make sure that the board is in flash memory mode. Hold the reset button on the Pico and connect it to the PC.
b) The Pico will now show as a USB storage device.
c) Copy the circuit python binary to the board and allow it to reboot.
d) Once it has rebooted the USB storage will show some directories – delete all of these.
e) Proceed to Step 2.
**Step 2** - Uploading Armachat COMPACT code to the Raspberry Pi Pico
a) Download the Armachat-circuit python code as a zip file using the green code button. Save to your PC.
f) Right click and extract all to a folder.
g) Browse to the software folder “…\Armachat-circuitpython-main\Armachat-circuitpython-main\Software”
h) Copy all files except those named “code TEST…py” to the Pico flash.
i) Once copied the Pico should reboot and now you are ready to go!
